### PR TITLE
Add process to quench energy deposits

### PR DESCRIPTION
**Pull request by lobis**
lobis Large: 503 [](https://github.com/rest-for-physics/geant4lib/commits/lobis-quenching)

Add a process to modify the energy of hits depending on the type of particle and volume name.

Documentation has been added to explain process and also unit test to check for the correct loading of rml file.

Example rml:
```
    <TRestGeant4QuenchingProcess>

        <volume name="^scintillatorVolume">
            <particle name="gamma" quenchingFactor="1.0"/>
            <particle name="e-" quenchingFactor="0.5"/>
            <particle name="e+" quenchingFactor="0.9"/>
            <particle name="mu-" quenchingFactor="0.2"/>
            <particle name="neutron" quenchingFactor="0.1"/>
        </volume>

        <volume name="gasVolume">
            <particle name="gamma" quenchingFactor="0.2"/>
            <particle name="e-" quenchingFactor="0.2"/>
        </volume>

    </TRestGeant4QuenchingProcess>
```

### CODE REVIEW

**Comment by lobis** [comment]
@jgalan seems the PR is still failing after the axionlib PR was merged?

**Comment by lobis** [comment]
This PR can now be merged, it was left hanging due to the problems in the pipeline that are now solved @jgalan

**Comment by lobis** [comment]
Please someone approve @rest-for-physics/core_dev

**Comment by juanangp** [comment]
Quenching factor is typically used for neutron recoils due to the fact that the nuclear recoil has less apparent deposited energy. I really don't understand how this is handle in this context, in case of neutrons the quenching factor should be applied to the nuclear recoil and not to the neutron itself.
For other particles, it migth makes sense depending on the interaction of the radiation with the detector, but I really don't understand the user case. E.g. in the example you apply the same quenching factor to electrons and gammas, but in fact the energy deposition of a gamma typically goes through photoelectric or Compton which led to an electron. In this case you would apply twice the quenching factor?

**Comment by glorialuzon** [comment]
I think it is not so direct.  You are comparing the ionization due to  electrons (photons don't produce any energy deposit until they create an electron) and that caused by other particles. I'm nor sure about muons or alpha particle, about how they compare to electrons.   If we consider the one of the recoiling nucleus (neutron doesn't ionize), it depends on the energy (slightly), and, of course on the recoiling nucleus. Have a look to this paper https://arxiv.org/abs/0712.2470 .

**Comment by lobis** [comment]
I is true that quenching should have a dependance on energy. However I think this PR can still be merged and the energy dependance of the quenching be an extension of the class defined here.

**Pull request merged**
