### PR TITLE
Fixed activeVolume for assemblies

### PR DESCRIPTION
**Pull request by lobis**
lobis Medium: 167 [](https://gitlab.cern.ch/rest-for-physics/geant4lib/-/commits/lobis-activeVolume-43) [](https://gitlab.cern.ch/rest-for-physics/restG4/-/commits/lobis-activeVolume-43) [](https://gitlab.cern.ch/rest-for-physics/framework/-/commits/lobis-activeVolume-43)

* Fixes https://github.com/rest-for-physics/restG4/issues/43
* Replaces `Nevents` by `nEvents` in RML files (`Nevents` still works) for consistency
* Replaces `gdml_file` by `gdmlFile` in RML files (`gdml_file` still works) for consistency
* Replaced "plate" by "circle" in generator, for consistency with Geant4 (also I don't think a plate is necessarily circular, its more like a "sheet")
* Other minor changes

### CODE REVIEW

**Review by juanangp — APPROVED** [review]

**Comment by jgalan** [comment]
If we change the value of the parameter name, at least it should follow the standards. The corresponding metadata member is `fGdmlFilename` then the parameter should be `gdmlFilename`. I do not mind changing the metadata member name, but the naming should be consistent.

Then, if we include `TRestMetadata::InitFromConfigFile` all the parameters matching their metadata member naming convention will be initialized with the RML values.

This could simplify the parameter retrieval in that method.

**Comment by jgalan** [comment]
I see now that `gdmFile` is actually the parameter, and `gdmlFilename` is formed internally. Still, if `TRestMetadata::InitFromConfigFile` is called, then we could initialize directly `fGdmlFilename`. Although the logic might need revision.

**Comment by jgalan** [comment]
We should probably throw `gdml_file` to adapt to the new naming conventions.

**Review by jgalan — APPROVED** [review]

**Comment by lobis** [comment]
> I see now that `gdmFile` is actually the parameter, and `gdmlFilename` is formed internally. Still, if `TRestMetadata::InitFromConfigFile` is called, then we could initialize directly `fGdmlFilename`. Although the logic might need revision.

I use explicit loading of the parameter to support both names for the parameter. I agree that the logic might need revision

**Pull request merged**
